const { Schema, model } = require("mongoose");

const RequestQuoteSchema = new Schema(
  {
    product_details: {
      type: Object,
    },
    delivery_mode: {
      type: String,
      required: [true, "Please Choose A Delivery Type"],
      enum: ["Sea", "Air"],
    },
    transportation_by: {
      type: String,
      required: [true, "Please Choose a Transportation way"],
      enum: ["FCL", "LCL", "Bulk", "SC", "ULDC"],
    },
    weight: {
      type: Number,
      required: [true, "Please specify weight"],
      default: 0,
    },
    volume: {
      type: Number,
      required: [true, "Please specify Volume"],
      default: 0,
    },
    by_units: { type: Boolean, default: false },
    dimensions: [Object],
    container_type: {
      type: String,
      required: [true, "Please Choose a container type"],
      enum: [
        "20' Standard",
        "40' Standard",
        "40' High-Cube",
        "20' Refrigerated",
        "40' Refrigerated",
        "20' Open Top",
        "40' Open Top",
        "20' Flatrack",
        "40' Flatrack",
        "20' Tank",
        "40' Flatrack Collapsible",
        "20' Flatrack Collapsible",
        "20' Platform",
        "40' Platform",
        "20' Bulk",
        "45' High-Cube",
        "10' Standard",
        "Demi",
        "HMA Stall",
        "LD-1",
        "LD-2",
        "LD-26",
        "LD-29",
        "LD-29 Reefer",
        "LD-3",
        "LD-3 Reefer",
        "LD-39",
        "LD-4",
        "LD-6",
        "LD-7",
        "LD-7 with Angled Wings",
        "LD-7 with Folding Wings",
        "LD-8",
        "LD-9",
        "LD-9 Reefer",
        "M-1",
        "M-1H",
        "M-2",
        "M-6",
        "M-6 (118H)",
        "M-6 Twin Car Rack",
        "MDP",
        "PLA Half Pallet",
        "PNP/P6P Pallet",
        "PNA Half Pallet",
        "Type A Pen",
        "N/A",
      ],
      default: "N/A",
    },
    ship_type: {
      type: String,
      required: [true, "Please Choose a container type"],
      enum: [
        "Bulk Careers",
        "Containerships",
        "General cargo",
        "Product tankers/Asphalt carriers",
        "Product tankers/Chemical tankers",
        "Product tankers/Crude carriers",
        "Product tankers/Gas carriers",
        "Specialized/Heavy-lift",
        "Specialized/Livestock",
        "Specialized/Refrigerated",
        "Specialized/RoRo",
        "Specialized/Wood chip",
        "N/A",
      ],
      default: "N/A",
    },
    ship_type: {
      type: String,
      required: [true, "Please Choose a container type"],
      enum: [
        "Bulk Careers",
        "Containerships",
        "General cargo",
        "Product tankers/Asphalt carriers",
        "Product tankers/Chemical tankers",
        "Product tankers/Crude carriers",
        "Product tankers/Gas carriers",
        "Specialized/Heavy-lift",
        "Specialized/Livestock",
        "Specialized/Refrigerated",
        "Specialized/RoRo",
        "Specialized/Wood chip",
        "N/A",
      ],
      default: "N/A",
    },
    gross_weight: {
      type: Number,
      required: [true, "Please specify Gross weight"],
      default: 0,
    },
    loading_rate: {
      type: Number,
      required: [true, "Please specify loading rate"],
      default: 0,
    },
    discharging_rate: {
      type: Number,
      required: [true, "Please specify discharging rate"],
      default: 0,
    },
    containers_quantity: { type: Number },
    location_from: {
      type: String,
      required: [true, "Please Enter Starting Destination"],
    },
    location_to: {
      type: String,
      required: [true, "Please Enter Ending Destination"],
    },
    ready_to_load: { type: String },
    additional_information: { type: String },
    associated_services: { type: String },
    first_name: { type: String, required: [true, "Please Enter First Name"] },
    last_name: { type: String, required: [true, "Please Enter Last Name"] },
    phone: {
      type: String,
      required: [true, "Please Enter Valid Phone Number"],
    },
    email: {
      type: String,
      required: [true, "Please Enter a Valid Email Address"],
    },
  },
  { timestamps: true }
);

const RQ = model("RequestQuotes", RequestQuoteSchema);

module.exports = RQ;
